baseurl = "https://laurent35240.github.io"
title = "Laurent Clouet"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = """
                Director of Engineering at <a href=\"https://www.westwing.de" target=\"_blank\">Westwing</a><br/>
                Experienced leader of engineering teams<br/>
                extensive expertise in web and cloud software development<br/>
                Proud to be geek"""
  logo = "fa-code"
  copyright = "Laurent Clouet"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/laurent35240"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/laurent-clouet-a7ba8721/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/laurent35240"

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.fr]
languageName = "Français"
weight = 2
title = "Laurent Clouet"
description = """
Director of Engineering chez <a href=\"https://www.westwing.de\" target=\"_blank\">Westwing</a><br/>
Leader Senior d'équipes d'ingénieurs<br/>
Vaste expertise dans le développement de logiciels Web et Cloud<br/>
Fièr d'être geek"""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

