baseurl = "https://laurent35240.github.io"
title = "Laurent Clouet"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = """
                Tech Lead / Senior Software Engineer at <a href=\"https://www.westwing.de" target=\"_blank\">Westwing</a><br/>
                10+ years of web backend development - Proud to be geek"""
  logo = "fa-code"
  copyright = "Laurent Clouet"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/laurent35240"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/laurent-clouet-a7ba8721/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/laurent35240"

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.fr]
languageName = "Français"
weight = 2
title = "Laurent Clouet"
description = """
Tech Lead / Ingénieur Logiciel chez <a href=\"https://www.westwing.de\" target=\"_blank\">Westwing</a><br/>
10+ années d'expériences dans le dévelopement web - Fièr d'être geek"""

